-- Supabase Schema for TeleFlow / Crypto Bot Copier
-- Run this SQL in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)

-- 1. Settings Table
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 2. Workflows Table
CREATE TABLE IF NOT EXISTS workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    source_channel TEXT,
    source_channel_id TEXT,
    target_channel TEXT,
    target_channel_id TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- 3. Rules Table
CREATE TABLE IF NOT EXISTS rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT REFERENCES workflows(id) ON DELETE CASCADE,
    rule_type TEXT,
    search_text TEXT,
    replace_text TEXT,
    time_min TEXT,
    time_max TEXT
);

-- 4. CTO Signals Table
CREATE TABLE IF NOT EXISTS cto_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ca TEXT,
    name TEXT,
    platform TEXT,
    market_cap TEXT,
    age TEXT,
    migration_age TEXT,
    perf_5m REAL,
    perf_1h REAL,
    perf_6h REAL,
    perf_24h REAL,
    status TEXT,
    dex_url TEXT,
    migration_status TEXT,
    workflow_id BIGINT,
    signal_type TEXT DEFAULT 'approved',
    payment_timestamp BIGINT,
    order_status TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Wallet Payments Table (Enriched with token & performance details)
CREATE TABLE IF NOT EXISTS wallet_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracked_address TEXT,
    sender_address TEXT,
    amount REAL,
    mint TEXT,
    signature TEXT UNIQUE,
    timestamp BIGINT,
    token_name TEXT,
    ca TEXT,
    platform TEXT,
    market_cap TEXT,
    age TEXT,
    migration_age TEXT,
    perf_5m REAL,
    perf_1h REAL,
    perf_6h REAL,
    perf_24h REAL,
    dex_url TEXT,
    migration_status TEXT,
    status TEXT,
    reason TEXT,
    formatted_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE cto_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_payments ENABLE ROW LEVEL SECURITY;

-- Allow full access for anon/service_role keys
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'settings' AND policyname = 'Allow all operations on settings') THEN
        CREATE POLICY "Allow all operations on settings" ON settings FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'workflows' AND policyname = 'Allow all operations on workflows') THEN
        CREATE POLICY "Allow all operations on workflows" ON workflows FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'rules' AND policyname = 'Allow all operations on rules') THEN
        CREATE POLICY "Allow all operations on rules" ON rules FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'cto_signals' AND policyname = 'Allow all operations on cto_signals') THEN
        CREATE POLICY "Allow all operations on cto_signals" ON cto_signals FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_payments WHERE tablename = 'wallet_payments' AND policyname = 'Allow all operations on wallet_payments') THEN
        CREATE POLICY "Allow all operations on wallet_payments" ON wallet_payments FOR ALL USING (true) WITH CHECK (true);
    END IF;
EXCEPTION
    WHEN undefined_table THEN
        NULL;
    WHEN others THEN
        NULL;
END $$;
